### ISSUE TITLE
The graphics viewer isn't available in step mode

### ISSUE THREAD

**Issue by 0x8BitDev** [pce-devel/mednafenPceDev#94]
In step mode (Alt+A), the graphics viewer (Alt+2) is not available. It would be nice to see what happens to sprites and tiles when step mode is active.

**Comment by dshadoff** [comment]
Rather than figure out how to make Alt_A work in the debugger series of windows, I have taken the new debugger functionality to "Step forward a frame" (CTRL+s) and "Step forward a scanline" (SHIFT+s), and extended it to all of the debugger windows:
- Disassembler
- Graphics viewer
- Memory viewer
- Log Viewer

However, only the disassembler viewer will step by CPU instructions.

**Comment by 0x8BitDev** [comment]
Everything works. Thanks!
